name: Publish Api documentations to GitHub pages

on:
    repository_dispatch:
        types: run-build-api-docs
    workflow_dispatch:
    schedule:
        - cron: "00 12 * * *"

jobs:
    publish-pages:
        environment:
            name: API documentations
            url: https://doctum.long-term.support/api-docs/
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ssh-key: ${{ secrets.SSH_KEY_DEPLOY }}
            - name: Import GPG key
              # v4 - 8c43807e82148a7bafc633cc9584d04bf54be8d0
              uses: crazy-max/ghaction-import-gpg@8c43807e82148a7bafc633cc9584d04bf54be8d0
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GPG_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
            - name: Build docs and push changes
              run: ./scripts/update-built-docs.sh
