name: Run tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
    test-php:
        name: Test on php ${{ matrix.php-version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            matrix:
                php-version: ["7.1"]
                os: [ubuntu-latest]
                experimental: [false]
                composer-options: ['']
        steps:
            - uses: actions/checkout@v2
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: posix, mbstring
                  coverage: xdebug
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install --no-interaction ${{ matrix.composer-options }}
            - name: Run php tests
              run: composer run phpunit
            - name: Send coverage
              uses: codecov/codecov-action@v1

    test-phar:
        name: Run command line tests on the phar with php ${{ matrix.php-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            fail-fast: false
            matrix:
                php-version: ["7.1"]
                os: [ubuntu-latest]
                experimental: [false]
                composer-options: ['']
        steps:
            - uses: actions/checkout@v2
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/v2.1.8.tar.gz
                  key: shunit2-cache
            - name: Setup shunit 2
              run: ./tests/phar/install-tests.sh
            - name: Run phar tests
              run: |
                export PATH="$PATH:$HOME/shunit2-2.1.8/"
                COMPOSER_BIN="/bin/composer" COMPOSER_OPTIONS="${{ matrix.composer-options }}" ./tests/phar/tests.sh

    test-resume-from-parse:
        name: Run resume from parse tests with php ${{ matrix.php-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            fail-fast: false
            matrix:
                php-version: ["7.1"]
                os: [ubuntu-latest]
                experimental: [true]
                composer-options: ['']
        steps:
            - uses: actions/checkout@v2
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install --no-interaction ${{ matrix.composer-options }}
            - name: Run resume from parse diff tests
              run: ./tests/resume-from-parse-test.sh
